/**
 * `npm run gen`: validate the declaration (src/resources/) and write src/generated/ and docs/reference/.
 * Template strings all the way down; there is no AST work here.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { flatten, validate, type Api, type FieldSpec, type Fields, type FlatAction, type ResourceSpec } from "../src/core/define.js";
import { api } from "../src/resources/index.js";

const HEADER = `// GENERATED by scripts/generate.ts from src/resources/. Do not edit. Run \`npm run gen\`.\n`;

// ─── Small helpers ────────────────────────────────────────────────────

/** `Foo bar` → `/** Foo bar *\/` on its own line at the given indent. */
function jsdoc(text: string, indent: string): string {
  const lines = text.trim().split("\n");
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((l) => `${indent} * ${l}`).join("\n")}\n${indent} */\n`;
}
/** Property key, quoted when not an identifier (e.g. `"eventID;year"`). */
const key = (k: string): string => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
const ident = (s: string) => /^[A-Za-z_$][\w$]*$/.test(s);
const pascal = (s: string): string => s.replace(/(^|[^A-Za-z0-9])([a-z0-9])/g, (_, __, c: string) => c.toUpperCase());
/** `event.get` → `EventGet`; `judging.team.review` → `JudgingTeamReview`. */
const typeName = (a: FlatAction) => pascal(a.key.replace(/\./g, "_"));
const hasRequired = (fields: Record<string, { optional?: boolean }>) => Object.values(fields).some((f) => !f.optional);
/** A keyless resource named after its scope sits directly on the scope: `bt.judging(e, y).get()`. */
const onScope = (r: ResourceSpec) => !!r.scope && r.singular === r.scope.name && !Object.keys(r.key).length;

// ─── TypeScript and Zod for one field ─────────────────────────────────

function tsType(f: FieldSpec, indent = ""): string {
  const t = (() => {
    switch (f.kind) {
      case "string": return "string";
      case "integer": case "number": return "number";
      case "boolean": return "boolean";
      case "json": return "unknown";
      case "enum": return f.values.map((v) => JSON.stringify(v)).join(" | ");
      case "ref": return f.entity;
      case "array": {
        const inner = tsType(f.items, indent);
        return f.items.kind === "object" || f.items.kind === "enum" || f.items.nullable ? `Array<${inner}>` : `${inner}[]`;
      }
      case "record": return `Record<string, ${tsType(f.values, indent)}>`;
      case "object": return `{\n${tsFields(f.fields, indent + "  ")}${indent}}`;
    }
  })();
  return f.nullable ? `${t} | null` : t;
}
function tsFields(fields: Fields, indent: string): string {
  let out = "";
  for (const [k, f] of Object.entries(fields)) out += jsdoc(f.description, indent) + `${indent}${key(k)}${f.optional ? "?" : ""}: ${tsType(f, indent)};\n`;
  return out;
}
function zodExpr(f: FieldSpec, indent = ""): string {
  const base = (() => {
    switch (f.kind) {
      case "string": return "z.string()";
      case "integer": return "z.number().int()";
      case "number": return "z.number()";
      case "boolean": return "z.boolean()";
      case "json": return "z.unknown()";
      case "enum": return `z.enum([${f.values.map((v) => JSON.stringify(v)).join(", ")}])`;
      case "ref": return `z.lazy(() => ${f.entity}Schema)`;
      case "array": return `z.array(${zodExpr(f.items, indent)})`;
      case "record": return `z.record(z.string(), ${zodExpr(f.values, indent)})`;
      case "object": return `z.object({\n${zodFields(f.fields, indent + "  ")}${indent}})`;
    }
  })();
  return `${base}${f.nullable ? ".nullable()" : ""}${f.optional ? ".optional()" : ""}`;
}
function zodFields(fields: Fields, indent: string): string {
  let out = "";
  for (const [k, f] of Object.entries(fields)) out += `${indent}${key(k)}: ${zodExpr(f, indent)},\n`;
  return out;
}

/** `bt.judging(…).team(…).review` — how the call reads in prose and docs. */
function chainOf(a: FlatAction): string {
  const r = a.resource;
  const scope = r.scope ? `${r.scope.name}(${Object.keys(r.scope.key).join(", ")}).` : "";
  if (a.level === "collection") return `bt.${scope}${r.plural}.${a.name}`;
  if (onScope(r)) return `bt.${scope}${a.name}`;
  return Object.keys(r.key).length ? `bt.${scope}${r.singular}(${Object.keys(r.key).join(", ")}).${a.name}` : `bt.${scope}${r.singular}.${a.name}`;
}

// ─── schemas.ts ───────────────────────────────────────────────────────

function emitSchemas(o: Api): string {
  let out = `${HEADER}import { z } from "zod";\n\n// ─── Entities ───\n\n`;
  for (const e of Object.values(o.entities)) {
    out += jsdoc(e.description, "");
    out += `export interface ${e.name} {\n${tsFields(e.fields, "  ")}}\n`;
    out += `export const ${e.name}Schema: z.ZodType<${e.name}> = z.object({\n${zodFields(e.fields, "  ")}});\n\n`;
  }
  out += `// ─── Action inputs and outputs ───\n\n`;
  for (const a of flatten(o)) {
    const n = typeName(a);
    const call = chainOf(a);
    if (a.spec.input) out += jsdoc(`Input for \`${call}\`.`, "") + `export interface ${n}Input {\n${tsFields(a.spec.input, "  ")}}\n`;
    // The wire schema validates key + input together; the caller-facing type is input only.
    out += `export const ${n}WireSchema = z.object({\n${zodFields(a.fullInput, "  ")}});\n`;
    out += `/** Everything the server receives for \`${call}\`: scope key, resource key, and input. */\nexport type ${n}Wire = z.infer<typeof ${n}WireSchema>;\n`;
    out += jsdoc(`Output of \`${call}\`. ${a.spec.output.description}`, "");
    out += `export type ${n}Output = ${tsType(a.spec.output)};\n`;
    out += `export const ${n}OutputSchema: z.ZodType<${n}Output> = ${zodExpr(a.spec.output)};\n\n`;
  }
  return out;
}

// ─── errors.ts ────────────────────────────────────────────────────────

function emitErrors(o: Api): string {
  const seen = new Map<string, string>();
  for (const a of flatten(o)) for (const [name, e] of Object.entries(a.spec.errors)) if (!seen.has(name)) seen.set(name, e.description);
  let out = `${HEADER}import { BtError } from "../core/runtime.js";\n\nexport { BtError, ApiError, NotAuthenticatedError, InputError, ContractViolationError } from "../core/runtime.js";\n\n`;
  for (const [name, desc] of seen) out += jsdoc(desc, "") + `export class ${name}Error extends BtError {\n  override readonly name = "${name}Error";\n}\n\n`;
  return out;
}

// ─── client.ts ────────────────────────────────────────────────────────

function actionDoc(o: Api, a: FlatAction): string {
  const errs = Object.entries(a.spec.errors).map(([en, e]) => `\`${en}Error\` (${e.status}) ${e.description}`);
  return [a.spec.description, ``, `Auth: \`${a.spec.auth}\` — ${o.roles[a.spec.auth]?.description ?? ""}`, `Route: \`${a.spec.route.method} ${a.spec.route.path}\``, ...(errs.length ? [`Throws: ${errs.join("; ")}`] : [])].join("\n");
}
/** `(input: S.XInput)`, `(input: S.XInput = {})`, or `()`. */
function param(a: FlatAction): { sig: string; arg: string } {
  if (!a.spec.input || !Object.keys(a.spec.input).length) return { sig: "", arg: "{}" };
  return { sig: hasRequired(a.spec.input) ? `input: S.${typeName(a)}Input` : `input: S.${typeName(a)}Input = {}`, arg: "input" };
}

function emitClient(o: Api): string {
  const flat = flatten(o);
  const byKey = new Map(flat.map((a) => [a.key, a]));
  let out = `${HEADER}import { Runtime, type ActionMeta, type ClientConfig } from "../core/runtime.js";\nimport * as S from "./schemas.js";\nimport * as E from "./errors.js";\n\n`;

  out += `const meta = {\n`;
  for (const a of flat) {
    const r = a.spec.route;
    const errors = Object.entries(a.spec.errors).map(([en, e]) => `${e.status}: E.${en}Error`).join(", ");
    out += `  "${a.key}": {\n    key: "${a.key}", method: "${r.method}", path: ${JSON.stringify(r.path)}, query: ${JSON.stringify(r.query ?? [])}, fixedQuery: ${JSON.stringify(r.fixedQuery ?? {})},\n`;
    out += `    auth: "${a.spec.auth}", credential: "${o.roles[a.spec.auth]!.credential}", input: S.${typeName(a)}WireSchema, output: S.${typeName(a)}OutputSchema, errors: { ${errors} },\n  },\n`;
  }
  out += `} satisfies Record<string, ActionMeta>;\n\n`;

  // One resource at a given indent; `chain` is the variables already bound by enclosing closures (scope key).
  const emitResource = (r: ResourceSpec, indent: string, chain: string[]): string => {
    let s = "";
    const collection = flat.filter((a) => a.resource === r && a.level === "collection");
    const instance = flat.filter((a) => a.resource === r && a.level === "instance");
    const keyNames = Object.keys(r.key);
    const merged = (vars: string[], hasInput: boolean) => (vars.length ? `{ ${vars.map(key).join(", ")}${hasInput ? ", ...input" : ""} }` : hasInput ? "input" : "{}");
    const actions = (acts: FlatAction[], vars: string[], inner: string) => {
      let b = "";
      for (const a of acts) {
        const { sig, arg } = param(a);
        b += jsdoc(actionDoc(o, a), inner) + `${inner}${key(a.name)}: (${sig}) => rt.call<S.${typeName(a)}Output>(meta["${a.key}"], ${merged(vars, arg === "input")}),\n`;
      }
      return b;
    };
    const links = (inner: string) => {
      let b = "";
      for (const [lk, l] of Object.entries(r.links)) {
        const target = byKey.get(l.via)!;
        const mapping = Object.entries(l.map).map(([inF, keyF]) => `${key(inF)}: ${ident(keyF) ? keyF : `key_${keyF}`}`).join(", ");
        b += jsdoc(`${l.description}\n\nLink → \`${l.via}\`. One HTTP call.`, inner) + `${inner}${key(lk)}: () => rt.call<S.${typeName(target)}Output>(meta["${l.via}"], { ${mapping} }),\n`;
      }
      return b;
    };
    if (collection.length) s += jsdoc(r.description, indent) + `${indent}${key(r.plural!)}: {\n${actions(collection, chain, indent + "  ")}${indent}},\n`;
    if (onScope(r)) return s + actions(instance, chain, indent) + links(indent);
    if (instance.length || Object.keys(r.links).length) {
      const vars = [...chain, ...keyNames];
      s += jsdoc(r.description, indent);
      if (keyNames.length) {
        const sig = keyNames.map((k) => `${ident(k) ? k : `key_${k}`}: ${tsType(r.key[k]!)}`).join(", ");
        s += `${indent}${key(r.singular)}: (${sig}) => ({\n${actions(instance, vars, indent + "  ")}${links(indent + "  ")}${indent}}),\n`;
      } else s += `${indent}${key(r.singular)}: {\n${actions(instance, vars, indent + "  ")}${links(indent + "  ")}${indent}},\n`;
    }
    return s;
  };

  out += jsdoc("Create a client. One per app, at startup. Every method is exactly one HTTP call to the BizTech API.\nSee README.md in this package for worked examples.", "");
  out += `export function createClient(config: ClientConfig) {\n  const rt = new Runtime(config);\n  return {\n`;
  const scoped = new Map<string, ResourceSpec[]>();
  for (const r of Object.values(o.resources)) {
    if (!r.scope) out += emitResource(r, "    ", []);
    else scoped.set(r.scope.name, [...(scoped.get(r.scope.name) ?? []), r]);
  }
  for (const [name, rs] of scoped) {
    const scope = rs[0]!.scope!;
    const keyNames = Object.keys(scope.key);
    const sig = keyNames.map((k) => `${k}: ${tsType(scope.key[k]!)}`).join(", ");
    out += jsdoc(scope.description, "    ") + `    ${key(name)}: (${sig}) => ({\n`;
    for (const r of rs) out += emitResource(r, "      ", keyNames);
    out += `    }),\n`;
  }
  out += `  };\n}\n\nexport type BtClient = ReturnType<typeof createClient>;\n`;
  return out;
}

// ─── docs/reference/ ────────────────────────────────────────────────────────────

function fieldRows(fields: Record<string, { kind: string; optional?: boolean; nullable?: boolean; description: string }>): string {
  return Object.entries(fields).map(([k, f]) => `| \`${k}\` | ${f.kind}${f.nullable ? " \\| null" : ""}${f.optional ? "?" : ""} | ${f.description.replace(/\|/g, "\\|")} |`).join("\n");
}
const outLink = (f: { kind: string; entity?: string; items?: { kind: string; entity?: string } }): string =>
  f.kind === "ref" ? `[${f.entity}](./entities.md#${f.entity!.toLowerCase()})` : f.kind === "array" && f.items?.kind === "ref" ? `[${f.items.entity}](./entities.md#${f.items.entity!.toLowerCase()})[]` : f.kind;

function emitDocs(o: Api): Record<string, string> {
  const files: Record<string, string> = {};
  const flat = flatten(o);
  let index = `# @ubc-biztech/sdk — reference\n\nGenerated from the declaration in src/resources/. Every fact here is also in the JSDoc; this is the same information for readers who are not in an editor.\n\n## Roles\n\n| Role | Meaning |\n|---|---|\n`;
  for (const [r, s] of Object.entries(o.roles)) index += `| \`${r}\` | ${s.description} |\n`;
  index += `\n## Resources\n\n`;
  for (const r of Object.values(o.resources)) {
    const acts = flat.filter((a) => a.resource === r);
    const docName = onScope(r) ? r.scope!.name : r.scope ? `${r.scope.name}.${r.singular}` : r.singular;
    index += `- [\`${docName}\`](./${docName}.md) — ${acts.map((a) => `\`${chainOf(a)}\``).join(", ")}${Object.keys(r.links).length ? ` · links: ${Object.keys(r.links).map((l) => `\`${l}\``).join(", ")}` : ""}\n`;
    let md = `# \`${docName}\`\n\n${r.description}\n\n`;
    if (r.scope) md += `Scoped under \`bt.${r.scope.name}(${Object.keys(r.scope.key).join(", ")})\`: ${r.scope.description}\n\n`;
    if (Object.keys(r.key).length) md += `**Key** (positional arguments of \`bt.${r.singular}(…)\`)\n\n| Field | Type | Description |\n|---|---|---|\n${fieldRows(r.key)}\n\n`;
    for (const a of acts) {
      const hasIn = a.spec.input && Object.keys(a.spec.input).length;
      md += `## \`${chainOf(a)}(${hasIn ? "input" : ""})\`\n\n${a.spec.description}\n\n- **Auth:** \`${a.spec.auth}\`\n- **Route:** \`${a.spec.route.method} ${a.spec.route.path}\`${a.spec.route.fixedQuery ? ` with \`?${new URLSearchParams(a.spec.route.fixedQuery)}\`` : ""}\n`;
      if (hasIn) md += `\n**Input**\n\n| Field | Type | Description |\n|---|---|---|\n${fieldRows(a.spec.input!)}\n`;
      md += `\n**Output:** ${outLink(a.spec.output)} — ${a.spec.output.description}\n`;
      const errs = Object.entries(a.spec.errors);
      if (errs.length) md += `\n**Errors**\n\n| Error | HTTP | When |\n|---|---|---|\n${errs.map(([en, e]) => `| \`${en}Error\` | ${e.status} | ${e.description} |`).join("\n")}\n`;
      md += `\n`;
    }
    const links = Object.entries(r.links);
    if (links.length) {
      md += `## Links\n\n| Call | Via | Description |\n|---|---|---|\n`;
      for (const [lk, l] of links) md += `| \`${chainOf({ resource: r, level: "instance", name: lk } as FlatAction)}()\` | \`${l.via}\` | ${l.description} |\n`;
      md += `\n`;
    }
    files[`${docName}.md`] = md;
  }
  index += `- [Entities](./entities.md)\n`;
  let ents = `# Entities\n\n`;
  for (const e of Object.values(o.entities)) {
    ents += `## ${e.name}\n\n${e.description}\n\n`;
    if (e.storage) ents += `Storage: table \`${e.storage.table}\`, pk \`${e.storage.pk}\`${e.storage.sk ? `, sk \`${e.storage.sk}\`` : ""}.\n\n`;
    ents += `| Field | Type | Description |\n|---|---|---|\n${fieldRows(e.fields)}\n\n`;
  }
  files["entities.md"] = ents;
  files["README.md"] = index;
  return files;
}

// ─── Run ──────────────────────────────────────────────────────────────

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = process.argv[2] ?? join(root, "src", "generated");
const docsDir = process.argv[3] ?? join(root, "docs", "reference");

validate(api);
for (const d of [outDir, docsDir]) {
  rmSync(d, { recursive: true, force: true });
  mkdirSync(d, { recursive: true });
}
const files: Record<string, string> = {
  "schemas.ts": emitSchemas(api),
  "errors.ts": emitErrors(api),
  "client.ts": emitClient(api),
  // Canonical JSON of the declaration; semver.ts diffs two of these.
  "api.json": JSON.stringify(api, null, 2) + "\n",
};
for (const [name, content] of Object.entries(files)) writeFileSync(join(outDir, name), content);
for (const [name, content] of Object.entries(emitDocs(api))) writeFileSync(join(docsDir, name), content);
const nLinks = Object.values(api.resources).reduce((n, r) => n + Object.keys(r.links).length, 0);
console.log(`sdk: ${Object.keys(api.entities).length} entities, ${Object.keys(api.resources).length} resources, ${flatten(api).length} actions, ${nLinks} links → ${readdirSync(outDir).length} generated files, ${readdirSync(docsDir).length} docs`);
